app = "kwik-ecommerce-api"
primary_region = "gru"

[build]
image = "kwik-ecommerce-api:latest"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[http_service.concurrency]
type = "requests"
hard_limit = 200

[[http_service.checks]]
grace_period = "20s"
interval = "10m"
method = "GET"
path = "/api/actuator/health"
timeout = "5s"