server:
  port: 9000

spring:
  web:
    resources:
      static-locations: classpath:/webjars/
  liquibase:
    enabled: true
    change-log: classpath:migrations/changelog.xml
    default-schema: common
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOSTNAME}/kwik_ecommerce_db?ssl=false
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    driver-class-name: org.postgresql.Driver

springdoc:
  api-docs:
    enabled: true
    path: /docs/open-api
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  show-actuator: true
  swagger-ui:
    enabled: true
    filter: true
    path: /docs/swagger-ui
    disable-swagger-default-url: true
    try-it-out-enabled: true
  packages-to-scan: br.com.bagnascojhoel.kwik_ecommerce

kwik:
  logging:
    whitelisted-headers:
      - content-type
    blacklisted-paths:
      - /docs/**/*
